
import {AppProvider} from "./Components/AppContext"
import { Roboto } from "next/font/google";
import "./globals.css";

import Providers from "./provider";
import Header from "./Header/page";
import { Toaster } from "react-hot-toast";
const roboto = Roboto({ subsets: ["latin"] , weight : ["400","500", "700"] });
 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
  <main className="max-w-9xl mx-[auto] p-4">
 
  <Providers>

  <AppProvider>
  <Toaster />
  <Header />
  {children}
  </AppProvider>
  </Providers>
  
  </main>
      </body>
    </html>
  );
}
